### ISSUE TITLE
default HEAD parameter

### ISSUE THREAD

**Issue by msartor92** [jtrussell/node-svn-info#3]
I'm using this package and I think it's very cool, but i think there is a conceptual error!
When I try to get svn info I want to get my working copy last revision code not repository head revision.
(I cant understand how to get it now)

So if you remove HEAD default parameter, we get three advantages: 
It works also offline, 
We can have last working copy revision code, 
We can specifing manually HEAD parameter we could had last repo revision data

**Comment by jtrussell** [comment]
Would you be able to use `BASE` as the revision? I believe this should correspond to the last revision you've fetched from the repository, i.e. whatever your working copy is as excluding modifications.

**Comment by msartor92** [comment]
Yes, you are right but 'svn info -r BASE' does not work offline. Differently 'svn info' works

**Comment by jtrussell** [comment]
Fair enough. To be honest in my usage I need to access the remote repo 100% of the time. That said, I'd be open to a PR where the default is to run `svn info` with no revision specified.

**Comment by jtrussell** [comment]
Closing this issue but like I said I'd be open to a PR or even talking through what that implementation might look like :).
