### ISSUE TITLE
Sync function errors on paths with spaces

### ISSUE THREAD

**Issue by alexbown** [jtrussell/node-svn-info#4]
When using the sync function with a path containing spaces in a folder name (such as "Program Files"), the sync function errors as it doesn't accept the full pathname into the svn info, instead using the path up to the space.
Code to handle this is already in the async function:-
`  if(/\s/.test(path)) {
    path = path
      .replace(/^['"]+/g, '')
      .replace(/["']+$/g, '');
    path = '"' + path + '"';
  }`

**Comment by jtrussell** [comment]
Thanks - should be fixed in v0.2.2.
