### ISSUE TITLE
Allow calling svn info without `-r`

### ISSUE THREAD

**Issue by anhhnt** [jtrussell/node-svn-info#6]
I checked in code and see that in sync flavor, the argument `-r` is always passed. It means whenever this function is called, svn try to connect to svn server, and fail due to lacking of authentication credentials.
The async version works because `rev` parameter is not used at all.
Please allow calling sync `svn info` without `-r`. As this is a small modification, I can help with a PR.
Thank you.

**Comment by jtrussell** [comment]
Sure.

The async version should probably use `-r` if a revision is provided. I could see skipping `-r` though in both cases if if there's no provided revision. Feel free to submit a PR. Thanks.

**Comment by anhhnt** [comment]
Hi @jtrussell,

When do you plan to release v1.0.0?

**Comment by jtrussell** [comment]
It's already released :).
